### ISSUE TITLE
How to enable/disable retina support?

### ISSUE THREAD

**Issue by waqasss** [bueltge/WP-Image-Resizer#3]
Can we add parameter to tell it whether to generate retina image or not?

Thanks for the plugin.

**Comment by bueltge** [comment]
Which function do you use, or shortcode? It is easier to enhance your example to understand the how to.

**Comment by waqasss** [comment]
I'm using this method >> aq_resize( $img_url, $width );

**Comment by bueltge** [comment]
You find here the documentation about this function. I have enhance the docu for this param, is much newer and was not inside this page, but now.
https://github.com/bueltge/WP-Image-Resizer/wiki/Parameters#aqua-resizer

Helpful enough?

**Comment by waqasss** [comment]
Yeah thanks Bueltge (:
